### ISSUE TITLE
Can run on Windos OS

### ISSUE THREAD

**Issue by awalece04ku** [huangzhii/biolearns#1]
I can't run on the windows. Can you help plz?
import numpy as np
from biolearns.dataset import TCGA
from biolearns.preprocessing import expression_filter
brca = TCGA('BRCA')

#### Error
Retrieve mRNAseq from http://firebrowse.org/ ...
Cohort: Breast invasive carcinoma (BRCA)
File type: illuminahiseq_rnaseqv2-RSEM_genes_normalized
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-2-39cca8406d71> in <module>
----> 1 brca = TCGA('BRCA')

C:\ProgramData\Anaconda3\lib\site-packages\biolearns\dataset\_TCGA.py in __init__(self, cohort, download, location)
    100         if download:
    101 #            self.tmpdir = tempfile.TemporaryDirectory()
--> 102             self.mRNAseq = self.get_mRNAseq()
    103             self.miRNAseq = self.get_miRNAseq()
    104             self.mRNA = None

C:\ProgramData\Anaconda3\lib\site-packages\biolearns\dataset\_TCGA.py in get_mRNAseq(self)
    124 
    125         if not os.path.exists(file_downloaded):
--> 126             self._download_file(link, file_downloaded)
    127 
    128         if self.cohort in ['COADREAD', 'ESCA', 'GBM', 'HNSC', 'KIPAN', 'KIRC', 'KIRP', 'LAML', \

C:\ProgramData\Anaconda3\lib\site-packages\biolearns\dataset\_TCGA.py in _download_file(self, link, filename)
    221     def _download_file(self, link, filename):
    222         if not os.path.exists(filename):
--> 223             with open(filename, "wb") as f:
    224 #                    print("Downloading %s to %s" % (self.cohort, filename))
    225                     response = requests.get(link, stream=True)

FileNotFoundError: [Errno 2] No such file or directory: '/tmp\\BRCA.mRNAseq.tar.gz'

**Comment by huangzhii** [comment]
biolearns is not implemented in Windows, you are welcomed to pull requests.
